# Generated by Django 4.0.6 on 2023-05-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_usercart_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='cart_id_pk',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
