# Generated by Django 4.2 on 2023-05-03 12:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='product/')),
                ('description', ckeditor.fields.RichTextField()),
                ('country', models.CharField(max_length=250)),
                ('qty', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
