# Generated by Django 4.2 on 2023-05-12 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0006_alter_category_name_orders_orderitems_cartitems"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitems",
            name="order",
        ),
        migrations.RemoveField(
            model_name="orderitems",
            name="product",
        ),
        migrations.RemoveField(
            model_name="orders",
            name="user",
        ),
        migrations.DeleteModel(
            name="CartItems",
        ),
        migrations.DeleteModel(
            name="OrderItems",
        ),
        migrations.DeleteModel(
            name="Orders",
        ),
    ]
